function initMainPage(){
	$("#returnToMainBtn").on("click",function(){
		$.toMainPage.show();
	})
	$("#tags").createTags({
		source:"views/tags_page1.json",
		style:'tag',
		created:function(res){
			console.log(res);
		}
	})
	$("#imgLinks_mainPage").createdImgLinks({
		source:"views/imgLinks_mainPage.json",
		style:'link',
		created:function(res){
			console.log(res);
			$("#mainPage").css("display","none");
			$(".footer").css("display","block");
			$(".navBtn").each(function(){
				if($(this).attr("target")==res){
					$("#returnToMainBtn").css("display","block");
					$(".gap-bottom").css('display',"block");
					$(this).trigger('click');
				}
			})
		}
	})
}