$('#page3').on('pageInit',function(){
	$("#imgLinks_page3").createdImgLinks({
		source:"views/imgLinks_page3.json",
		style:'link',
		created:function(res){
		}
	})
})
$('#page3').on('pageShow',function(){
})