$('#page2').on('pageInit',function(){
	$("#modeName").html('我要教');
	$("#imgLinks_page2").createdImgLinks({
		source:"views/imgLinks_page2.json",
		style:'link',
		created:function(res){
		}
	})
	$("#tobeteacher").on("click",function(){
		open("regist.html?levelup=true","_self");
	})
})
$('#page2').on('pageShow',function(){
	$("#modeName").html('我要教');
})